spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:postgresql://localhost:5432/e-commerce
    username: e_commerce_user
    password: 123456
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-timeout: 30000
      maximum-pool-size: 20
  data:
    redis:
      host: localhost
      port: 6379
      password: 123456

server:
  port: 8080