spring:
  application:
    name: online-shop
  profiles:
    active: dev
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss

# 日志配置（通用）
logging:
  include-application-name: false
  level:
    root: INFO
  file:
    name: logs/e-commerce.log
  logback:
    rolling-policy:
      max-file-size: 10MB
      max-history: 30